
const Translations = {
    EN:{
        profit: "Count Profits",
        Product: "Products",
        Contact: "Contact",
        faq: "FAQ",
        navButton: "BUY",
        upperTxt: "A smart crusher that turns glass into sand.",
        innerTxt1: "Pay 5 times less for the disposal of glass waste.",
        innerTxt2: "The crusher reduces the size of glass rubbish, and you pay FIVE-TIMES-NO lower bills for their disposal.",
        saveTxt: "How much will you save?",
        billTxt: "The bill is simple.",
        boxTxt1: "How many glass containers",
        boxTxt2: "do you fill monthly",
        boxTxt3: "How much do you pay to export one",
        boxTxt4: "glass container?",
        lowTxt1: "Thanks to the crusher you will save",
        lowTxt2: "PLN 900",
        lowTxt3: "Annually.",
        lowTxt4: "What will you spend the saved cash on?",
        lowTxt5: "BUY PLN 8499",
        lowTxt6: "Sounds good? Be careful. We're just getting started!",
        languageValue: "EN",

    },
    DE:{
        profit: "Zählen Sie Ihre Gewinne",
        Product: "Über das Produkt",
        Contact: "Kontakt",
        faq: "FAQ",
        navButton: "KAUFEN",
        upperTxt: "Ein intelligenter Brecher, der Glas in Sand verwandelt.",
        innerTxt1: "Zahlen Sie 5-mal weniger für die Entsorgung von Glasabfällen.",
        innerTxt2: "Der Crusher zerkleinert den Glasabfall und Sie bezahlen FÜNF MAL NIE weniger Rechnungen für deren Entsorgung.",
        saveTxt: "Wie viel werden Sie sparen?",
        billTxt: "Die Rechnung ist einfach.",
        boxTxt1: "Wie viele Glasbehälter",
        boxTxt2: "füllst du monatlich",
        boxTxt3: "Wie viel zahlen Sie für den Export?",
        boxTxt4: "Glas-Container?",
        lowTxt1: "Dank des Brechers sparen Sie",
        lowTxt2: "900 PLN",
        lowTxt3: "jährlich.",
        lowTxt4: "Wofür geben Sie das gesparte Geld aus?",
        lowTxt5: "KAUFEN 8499 PLN",
        lowTxt6: "Klingt gut? Vorsichtig sein. Wir fangen gerade erst an!",
        languageValue: "DE",
    },
    PL:{
        profit:"Policz zyski",
        Product:"O produkcie",
        Contact:"Kontakt",
        faq:"FAQ",
        navButton:"KUP",
        upperTxt:"Inteligentna kruszarka, która zamienia szkło w piasek.",
        innerTxt1:"Płać 5 razy mniej za wywóz odpadów szklanych.",
        innerTxt2:"Kruszarka zmniejsza gabaryty szklanych śmieci, a Ty płacisz PIĘ-CIO-KROT-NIE niższe rachunki za ich wywóz.",
        saveTxt:"Ile zaoszczędzisz?",
        billTxt:"Rachunek jest prosty.",
        boxTxt1:"Ile pojemników na szkło",
        boxTxt2:"zapełniasz miesięcznie?",
        boxTxt3:"Ile płacisz za wywóz jednego",
        boxTxt4:"pojemnika na szkło?",
        lowTxt1:"Dzięki kruszarce zaoszczędzisz",
        lowTxt2:"900 zł",
        lowTxt3:"rocznie",
        lowTxt4:"To na co wydasz zaoszczędzoną gotówkę?",
        lowTxt5:"KUP 8499 zł",
        lowTxt6:"Brzmi dobrze? Uważaj. Dopiero się rozkręcamy!",
        languageValue: "PL",
    }
    
};

